version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node
    executor: ruby/default
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      # bundle cache
      - restore_cache:
          keys:
            - my-annotations-{{ checksum "Gemfile.lock" }}
            - my-annotations-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      # Store bundle cache
      - save_cache:
          key: my-annotations-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
